
development:
  adapter: postgresql
  database: frotogo_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: frotogo_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: frotogo_production
  pool: 5
  timeout: 5000
